/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zoro2723.comicreader;

import FileHandler.FileList;
import database.DatabaseConnection;
import database.TableCheck;
import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import viewerPanelPackage.ImagePreviewHandler;
import zipPreprocessor.ZipPreprocessor;

/**
 *
 * @author zoro2723
 */
public class MainFrame extends javax.swing.JFrame {
    public static ImagePreviewHandler iph = new ImagePreviewHandler(); 
    private ArrayList<ZipPreprocessor> zipProcessList;
    private final FileList<File> fileList;
    //loaded statically.

    private final FilePanel filePanel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.fileList = initialize();

        this.filePanel = new FilePanel(fileList);
        iph.setTabbedPanel(RightPanel.getPane());
        initComponents();
        addComponent();

        startPreprocessing();

    }

   
    private void startPreprocessing() {
        ExecutorService executorService = Executors.newFixedThreadPool(4);  // Create a thread pool
        Connection con = DatabaseConnection.connect();

        if (!TableCheck.doesTableExist(con, "zip_files"))
            TableCheck.createTables(con);
        if (!TableCheck.doesTableExist(con, "image_previews"))
            TableCheck.createTables(con);
        
        for (Component item : filePanel.getRightPanel().getComponents()) {
            if (item instanceof FileItemComponent) {
                // zipProcessList.add(new ZipPreprocessor((FileItemComponent)item, con));
                executorService.submit(new ZipPreprocessor((FileItemComponent) item, con));
            }
        }
        
        executorService.shutdown();  // Shut down the executor after all tasks are submitted

    }

    private static FileList<File> initialize() {
        FileList<File> fileList;
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("fileList.dat"))) {
            fileList = (FileList<File>) ois.readObject(); // 'fileList' is your FileList instance
            System.out.println("FileList loaded successfully.");
        } catch (IOException | ClassNotFoundException e) {
            System.err.println("Error loading FileList: " + e.getMessage());
            // Handle the case where the file doesn't exist (e.g., first launch)
            fileList = new FileList<>(); // Create a new FileList if the file is not found
        }
        return fileList;
    }

    private void addComponent() {
        myTabbedPane.addTab("Files", filePanel);
        filePanel.setListener((MyTabbedPane)myTabbedPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myTabbedPane = new MyTabbedPane();
        tabs = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        imagePreviewScrollPane = new javax.swing.JScrollPane();
        thumbnailPanel = new javax.swing.JPanel();
        imageScrollPane = new javax.swing.JScrollPane();
        imageViewPanel = new javax.swing.JPanel();
        toolPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(2, 25), new java.awt.Dimension(32767, 50));
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMI = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        imagePreviewScrollPane.setPreferredSize(new java.awt.Dimension(120, 100));

        thumbnailPanel.setPreferredSize(new java.awt.Dimension(120, 302));
        imagePreviewScrollPane.setViewportView(thumbnailPanel);
        thumbnailPanel.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout imageViewPanelLayout = new javax.swing.GroupLayout(imageViewPanel);
        imageViewPanel.setLayout(imageViewPanelLayout);
        imageViewPanelLayout.setHorizontalGroup(
            imageViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        imageViewPanelLayout.setVerticalGroup(
            imageViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        imageScrollPane.setViewportView(imageViewPanel);
        imageViewPanel.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(imagePreviewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePreviewScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imageScrollPane)
        );

        toolPanel.setPreferredSize(new java.awt.Dimension(850, 50));

        jPanel1.setBorder(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(775, 50));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton1);

        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton2);

        jButton3.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton3);

        jButton4.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton4);

        jButton5.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton5);

        jButton6.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton6);
        jPanel1.add(filler1);

        jButton7.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton7);

        jButton8.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton8);

        jButton9.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel1.add(jButton9);

        jPanel2.setPreferredSize(jPanel1.getPreferredSize());
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jButton17.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton17);

        jButton16.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton16);

        jButton15.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton15);

        jButton14.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton14);

        jButton13.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton13);

        jButton12.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton12);

        jButton11.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton11);

        jButton10.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel2.add(jButton10);

        javax.swing.GroupLayout toolPanelLayout = new javax.swing.GroupLayout(toolPanel);
        toolPanel.setLayout(toolPanelLayout);
        toolPanelLayout.setHorizontalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        toolPanelLayout.setVerticalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addGroup(toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabsLayout = new javax.swing.GroupLayout(tabs);
        tabs.setLayout(tabsLayout);
        tabsLayout.setHorizontalGroup(
            tabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(tabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toolPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        tabsLayout.setVerticalGroup(
            tabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(tabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        menuBar.setBackground(new java.awt.Color(78, 78, 78));

        jMenu1.setText("File");
        jMenu1.setMargin(new java.awt.Insets(4, 8, 4, 8));

        openMI.setText("Open...");
        openMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMIActionPerformed(evt);
            }
        });
        jMenu1.add(openMI);

        jMenu7.setText("Recent");
        jMenu1.add(jMenu7);

        jMenuItem2.setText("Library...");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save As");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Refresh");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Properties");
        jMenu1.add(jMenuItem5);

        jMenu9.setText("Open with");
        jMenu1.add(jMenu9);

        jMenuItem6.setText("Delete");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Minimize");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Close");
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Save and quit");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Quit");
        jMenu1.add(jMenuItem10);

        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setMargin(new java.awt.Insets(4, 8, 4, 8));
        menuBar.add(jMenu2);

        jMenu3.setText("View");
        jMenu3.setMargin(new java.awt.Insets(4, 8, 4, 8));
        menuBar.add(jMenu3);

        jMenu4.setText("Go");
        jMenu4.setMargin(new java.awt.Insets(4, 8, 4, 8));
        menuBar.add(jMenu4);

        jMenu5.setText("Bookmarks");
        jMenu5.setMargin(new java.awt.Insets(4, 8, 4, 8));
        menuBar.add(jMenu5);

        jMenu6.setText("Tools");
        jMenu6.setMargin(new java.awt.Insets(4, 8, 4, 8));
        menuBar.add(jMenu6);

        jMenu8.setText("Help");
        jMenu8.setMargin(new java.awt.Insets(4, 8, 4, 8));
        menuBar.add(jMenu8);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(myTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(myTabbedPane)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void openMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMIActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Zip Files", "zip"));
        fileChooser.setDialogTitle("Select a Zip File");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setMultiSelectionEnabled(true);
        int returnValue = fileChooser.showOpenDialog(null); // For opening files
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            fileList.addAll(fileChooser.getSelectedFiles());
            filePanel.addFiles();
        }

    }//GEN-LAST:event_openMIActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("fileList.dat"))) {
            oos.writeObject(fileList); // 'fileList' is your FileList instance
            System.out.println("FileList saved successfully.");
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Error saving FileList: " + e.getMessage());
        }

    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

    }//GEN-LAST:event_jMenuItem4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane imagePreviewScrollPane;
    private javax.swing.JScrollPane imageScrollPane;
    private javax.swing.JPanel imageViewPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane myTabbedPane;
    private javax.swing.JMenuItem openMI;
    private javax.swing.JPanel tabs;
    private javax.swing.JPanel thumbnailPanel;
    private javax.swing.JPanel toolPanel;
    // End of variables declaration//GEN-END:variables

}
